apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapi
  template:
    metadata:
      labels:
        app: todoapi
    spec:
      containers:
        - image: "todoapi"
          imagePullPolicy: Never
          name: todoapi
          ports:
            - containerPort: 83


---
apiVersion: v1
kind: Service
metadata:
 name: todoapi
spec:
 type: NodePort
 selector:
   app: todoapi
 ports:
   - name: client
     protocol: TCP
     port: 83
     nodePort: 32081
 selector:
   app: todoapi