version: '3.4'
services:
  todoapi:
    depends_on:
        - db
    image: todoapi
    build:
        context: .
    ports:
        - "5000:83"
  
  db:
    image: mysqldocker
    build:
       context: ./MySQL/
       dockerfile: Dockerfile
    hostname: mysql
    ports:
      - "3306:3306"
    environment:
       MYSQL_RANDOM_ROOT_PASSWORD: mypassword
       MYSQL_DATABASE: todo
       MYSQL_USER: dbuser
       MYSQL_PASSWORD: dbuser
    restart: always
      
  omnidb:
    image: taivokasper/omnidb
    depends_on:
      - db
    ports:
      - "8081:8080"
      - "25482:25482"
    restart: unless-stopped
    